#pragma once
#define log(_format, ...) DbgPrintEx( DPFLTR_DEFAULT_ID, DPFLTR_INFO_LEVEL, "[Aos] "_format,##__VA_ARGS__ );
#define warn(_format, ...) DbgPrintEx( DPFLTR_DEFAULT_ID, DPFLTR_WARNING_LEVEL, "[Aos] [Warn] "_format,##__VA_ARGS__ );
#define err(_format, ...) DbgPrintEx( DPFLTR_DEFAULT_ID, DPFLTR_ERROR_LEVEL,"[Aos] [Err] " _format,##__VA_ARGS__ );

#define IOCTL_WRITE_MEMORY \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_READ_MEMORY \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x900, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_CHANGE_PROTECT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x950, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_ALLOCATE_MEMORY \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x960, METHOD_BUFFERED, FILE_ANY_ACCESS)